In [1]:
import pandas as pd

In [3]:
d1 = pd.read_parquet("predicts/imdb_classifier.pq")
d2 = pd.read_parquet("predicts/imdb_classifier_pretrained_200k.pq")
d1

,texto,sentiment,label,split,tokens,pred,modelo
0,"If you want a horrible interpretation of ""MacB...",negative,0,test,"[3803, 3303, 123, 640, 281, 2062, 321, 1167, 7...",0,imdb_classifier
1,Hm. Where do I start? I usually ignore whateve...,negative,0,test,"[76, 113, 50, 36, 773, 384, 1903, 739, 977, 12...",0,imdb_classifier
2,This is another one of those films that I reme...,positive,1,test,"[845, 306, 1887, 494, 278, 1800, 3881, 382, 73...",0,imdb_classifier
3,"I, like many other Bachchan fans, having been ...",negative,0,test,"[77, 48, 36, 1442, 1002, 607, 70, 547, 299, 30...",0,imdb_classifier
4,"Subtle, delicate ,touching.<br /><br />A young...",positive,1,test,"[2801, 120, 323, 48, 36, 1839, 287, 416, 48, 3...",1,imdb_classifier
...,...,...,...,...,...,...,...
4995,Saw this in the theater in '86 and fell out of...,positive,1,test,"[87, 1065, 655, 283, 269, 423, 1127, 283, 43, ...",1,imdb_classifier
4996,"Contains spoilers<br /><br />""Hollow Man"" is p...",positive,1,test,"[670, 120, 1338, 409, 115, 296, 495, 64, 538, ...",0,imdb_classifier
4997,I watched two very different Holmes adventures...,positive,1,test,"[739, 4288, 2381, 659, 1559, 1908, 2247, 113, ...",1,imdb_classifier
4998,i loved this movie it was one of the years bes...,positive,1,test,"[456, 112, 406, 275, 655, 3509, 260, 436, 320,...",1,imdb_classifier
4999,This program was shown in an early morning tim...,negative,0,test,"[845, 2929, 320, 4423, 283, 304, 1111, 2828, 1...",0,imdb_classifier

In [17]:
erros = d1[(d1["label"] != d1["pred"]) & (d2["label"] == d2["pred"])]
erros.head(20)

,texto,sentiment,label,split,tokens,pred,modelo
2,This is another one of those films that I reme...,positive,1,test,"[845, 306, 1887, 494, 278, 1800, 3881, 382, 73...",0,imdb_classifier
7,"Ok, I've seen plenty of movies dealing with wi...",negative,0,test,"[3683, 48, 36, 77, 43, 363, 2976, 343, 324, 27...",1,imdb_classifier
23,Interesting to read comments by viewers regard...,negative,0,test,"[2471, 437, 294, 295, 3781, 592, 576, 345, 138...",1,imdb_classifier
34,"Billy Crystal co-wrote, co-produced and stars ...",negative,0,test,"[70, 296, 378, 1644, 4435, 300, 641, 49, 1962,...",1,imdb_classifier
39,"What can you say about a grainy, poorly filmed...",negative,0,test,"[773, 317, 922, 3303, 119, 417, 869, 281, 407,...",1,imdb_classifier
48,There is so much of worth in this movie that i...,positive,1,test,"[1493, 306, 1348, 2086, 278, 470, 314, 283, 65...",0,imdb_classifier
54,"As so many others have written, this is a wond...",positive,1,test,"[1154, 1348, 1002, 4159, 635, 785, 1561, 48, 3...",0,imdb_classifier
69,After all the hype I had heard about the Jane ...,negative,0,test,"[1033, 446, 269, 1423, 116, 260, 739, 508, 243...",1,imdb_classifier
72,This movie tries to run away to the typical 'I...,positive,1,test,"[845, 3509, 260, 1059, 302, 295, 2681, 2891, 2...",0,imdb_classifier
81,I might have given this movie a higher rating ...,negative,0,test,"[739, 4835, 635, 2000, 655, 3509, 260, 281, 40...",1,imdb_classifier
85,"This amusing, sometimes poignant look at the H...",positive,1,test,"[845, 305, 331, 285, 48, 36, 3786, 498, 964, 6...",0,imdb_classifier
89,Lucasarts have pulled yet another beauty out o...,positive,1,test,"[3434, 309, 272, 435, 635, 4409, 1384, 125, 53...",0,imdb_classifier
99,Let me say at the outset that I'm not a very a...,negative,0,test,"[80, 530, 1830, 119, 417, 317, 269, 1013, 1333...",1,imdb_classifier
106,This film is awful. Give me the dentist anytim...,negative,0,test,"[845, 1015, 306, 477, 909, 50, 36, 75, 1890, 1...",1,imdb_classifier
120,I am a big 1930's movie fan and will watch mos...,negative,0,test,"[739, 513, 281, 102, 2023, 53, 61, 55, 52, 43,...",1,imdb_classifier
125,Curl up with this one on a dark and stormy nig...,positive,1,test,"[4391, 394, 708, 353, 655, 494, 288, 281, 3911...",0,imdb_classifier
128,This is on my TV right now... but only long en...,negative,0,test,"[845, 306, 288, 1368, 2039, 2095, 3694, 50, 50...",1,imdb_classifier
139,I give 3 stars only for the beautiful pictures...,negative,0,test,"[739, 4076, 55, 36, 977, 261, 839, 340, 269, 3...",1,imdb_classifier
152,There aren't too many times when I see a film ...,positive,1,test,"[1493, 272, 270, 43, 268, 4093, 1002, 1967, 81...",0,imdb_classifier
159,"This movie clearly has an agenda, which could ...",negative,0,test,"[845, 3509, 260, 2209, 1406, 524, 304, 330, 46...",1,imdb_classifier

In [18]:
escolhido = 34

In [23]:
from pprint import pprint
pprint(erros.loc[escolhido, "texto"])
print()
print(f"PREDIÇÃO: {'NEGATIVE' if erros.loc[escolhido, 'pred'] == 0 else 'POSITIVE'} - REAL: {'NEGATIVE' if erros.loc[escolhido, 'label'] == 0 else 'POSITIVE'}")

('Billy Crystal co-wrote, co-produced and stars in this extremely safe and '
 'comfy comedy-drama about fathers and sons, adult irresponsibility, and '
 'growing old. Billy plays a heart surgeon who has a heart attack (ha ha) '
 'which causes him to seek out his estranged father (Alan King), a movie-extra '
 'who fancies himself a big star. The script is sub-Neil Simon nonsense with '
 'one-liners galore, a flat, inexpressive direction by Henry Winkler (stuck in '
 'sitcom mode), and family-conflict at the ready. Crystal and King try their '
 'best, but King is over-eager and frequently over-the-top. JoBeth Williams '
 'has another one of her thankless roles, but manages to bring her innate, '
 "down-home class to the proverbial girlfriend character. It's a comedy, I "
 'guess, but one that blinks back the tears...shamefully. ** from ****')

PREDIÇÃO: POSITIVE - REAL: NEGATIVE

In [9]:
acertos = d2[d2["label"] == d2["pred"]]
acertos.head(20)

,texto,sentiment,label,split,tokens,pred,modelo
0,"If you want a horrible interpretation of ""MacB...",negative,0,test,"[3803, 3303, 123, 640, 281, 2062, 321, 1167, 7...",0,imdb_classifier_pretrained_200k
1,Hm. Where do I start? I usually ignore whateve...,negative,0,test,"[76, 113, 50, 36, 773, 384, 1903, 739, 977, 12...",0,imdb_classifier_pretrained_200k
2,This is another one of those films that I reme...,positive,1,test,"[845, 306, 1887, 494, 278, 1800, 3881, 382, 73...",1,imdb_classifier_pretrained_200k
3,"I, like many other Bachchan fans, having been ...",negative,0,test,"[77, 48, 36, 1442, 1002, 607, 70, 547, 299, 30...",0,imdb_classifier_pretrained_200k
4,"Subtle, delicate ,touching.<br /><br />A young...",positive,1,test,"[2801, 120, 323, 48, 36, 1839, 287, 416, 48, 3...",1,imdb_classifier_pretrained_200k
5,I kind of consider myself as the #1 fan of Hid...,positive,1,test,"[739, 111, 2016, 278, 1657, 286, 2410, 2100, 2...",1,imdb_classifier_pretrained_200k
6,If you are looking for a cinematic masterpiece...,negative,0,test,"[3803, 3303, 444, 4400, 294, 340, 281, 103, 40...",0,imdb_classifier_pretrained_200k
7,"Ok, I've seen plenty of movies dealing with wi...",negative,0,test,"[3683, 48, 36, 77, 43, 363, 2976, 343, 324, 27...",0,imdb_classifier_pretrained_200k
9,This film is terrible. I was really looking fo...,negative,0,test,"[845, 1015, 306, 360, 321, 4305, 50, 36, 739, ...",0,imdb_classifier_pretrained_200k
10,This movie was a pleasant surprise for me. In ...,positive,1,test,"[845, 3509, 260, 320, 281, 4210, 309, 640, 990...",1,imdb_classifier_pretrained_200k
11,This was Barbra Streisand's first television s...,positive,1,test,"[845, 320, 1117, 538, 281, 1705, 301, 379, 43,...",1,imdb_classifier_pretrained_200k
12,"Now that I have seen it, it was NOT what I was...",positive,1,test,"[82, 549, 382, 739, 635, 2976, 298, 48, 36, 43...",1,imdb_classifier_pretrained_200k
13,"no really, im not kidding around here folks, a...",negative,0,test,"[1102, 279, 1725, 48, 36, 1901, 596, 111, 433,...",0,imdb_classifier_pretrained_200k
15,So what's the big fuss out of making an INDIAN...,negative,0,test,"[87, 280, 338, 290, 43, 261, 269, 102, 2023, 1...",0,imdb_classifier_pretrained_200k
16,Though Cher and Cage are the focal points of t...,positive,1,test,"[465, 650, 401, 286, 282, 71, 500, 444, 269, 2...",1,imdb_classifier_pretrained_200k
18,"In 1850 in Yorkshire, a boy chimney-sweep is f...",positive,1,test,"[413, 53, 60, 57, 52, 36, 283, 1955, 3409, 48,...",1,imdb_classifier_pretrained_200k
20,STAR RATING: ***** Saturday Night **** Friday ...,positive,1,test,"[87, 88, 69, 1909, 86, 3744, 77, 82, 75, 62, 3...",1,imdb_classifier_pretrained_200k
21,Truly a great film... I stumbled onto it at th...,positive,1,test,"[726, 337, 274, 281, 3125, 900, 50, 50, 50, 36...",1,imdb_classifier_pretrained_200k
23,Interesting to read comments by viewers regard...,negative,0,test,"[2471, 437, 294, 295, 3781, 592, 576, 345, 138...",0,imdb_classifier_pretrained_200k
24,"Normally, movies stay out of the realm of ""dom...",positive,1,test,"[724, 113, 1725, 48, 36, 3509, 302, 284, 417, ...",1,imdb_classifier_pretrained_200k

In [22]:
pprint(acertos.loc[escolhido, "texto"])
print()
print(f"PREDIÇÃO: {'NEGATIVE' if acertos.loc[escolhido, 'pred'] == 0 else 'POSITIVE'} - REAL: {'NEGATIVE' if acertos.loc[escolhido, 'label'] == 0 else 'POSITIVE'}")

('Billy Crystal co-wrote, co-produced and stars in this extremely safe and '
 'comfy comedy-drama about fathers and sons, adult irresponsibility, and '
 'growing old. Billy plays a heart surgeon who has a heart attack (ha ha) '
 'which causes him to seek out his estranged father (Alan King), a movie-extra '
 'who fancies himself a big star. The script is sub-Neil Simon nonsense with '
 'one-liners galore, a flat, inexpressive direction by Henry Winkler (stuck in '
 'sitcom mode), and family-conflict at the ready. Crystal and King try their '
 'best, but King is over-eager and frequently over-the-top. JoBeth Williams '
 'has another one of her thankless roles, but manages to bring her innate, '
 "down-home class to the proverbial girlfriend character. It's a comedy, I "
 'guess, but one that blinks back the tears...shamefully. ** from ****')

PREDIÇÃO: NEGATIVE - REAL: NEGATIVE